version: '3'
services:
  # Distributed Tracing with Zipkin
  esedm-zipkin:
    image: openzipkin/zipkin
    container_name: esedm-zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    #depends_on:
    #  - storage
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    #environment:
      #- STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      #- MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    networks:
      - esedm-backend
 
# Network to be used across multiple services    
networks:
    esedm-backend:
        external: true
